---
# tasks file for k9s

######################################
### packages

- name: "K9s: Manage directory"
  become: true
  ansible.builtin.file:
    name: "{{ k9s_path }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  when:
    - k9s_bin_state != 'skip'

- name: "K9s: Download"
  become: true
  ansible.builtin.unarchive:
    src: "{{ k9s_url }}"
    dest: "{{ k9s_path }}"
    owner: root
    group: root
    mode: "0755"
    remote_src: true
    extra_opts:
      - --add-file
      - k9s
      - --strip-components=1
  when:
    - k9s_bin_state != 'skip'
