---
namespace: giftpilz0
name: kubernetes
version: 1.0.0

description: Ansible collection for kubernetes cluster
readme: README.md
license:
  - GPL-3.0-only

authors:
  - Moritz Schmidt <schmidtmoritz404@gmail.com>

tags:
  - linux
  - k3s
  - kubernetes

dependencies:
  ansible.posix: ">=1.0.0"

repository: https://github.com/giftpilz0/ansible-collection-kubernetes
