---
# tasks file for cilium

######################################
### jobs

- name: "Cilium: Install Helm"
  ansible.builtin.include_role:
    name: giftpilz0.kubernetes.helm
  vars:
    helm_arch: amd64
    helm_tag: 3.15.2

- name: "Cilium: Add chart repo"
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: "{{ cilium_repo_url }}"

- name: "Cilium: Deploy Cilium chart"
  become: true
  kubernetes.core.helm:
    name: cilium
    chart_version: "{{ cilium_version }}"
    chart_ref: cilium/cilium
    release_namespace: kube-system
    values: "{{ lookup('template', 'values.yaml.j2') | from_yaml }}"
    kubeconfig: "{{ cilium_kubeconfig }}"
