---
# tasks file for k3s

- name: "K3S: Manage k3s Service Unit File"
  ansible.builtin.template:
    src: k3s.service.j2
    dest: /etc/systemd/system/{{ k3s_service_name }}
    owner: root
    group: root
    mode: "0644"

- name: "K3S: Manage k3s Service"
  ansible.builtin.systemd:
    name: "{{ k3s_service_name }}"
    state: "{{ k3s_service_state }}"
    enabled: "{{ k3s_service_enabled }}"
    daemon_reload: true
