---
# defaults file for k3s

k3s_version: v1.30.2+k3s1

k3s_vip_api_endpoint: "{{ hostvars[groups['k3s'][0]]['ansible_host'] | default(groups['k3s'][0]) }}"
k3s_api_port: 6443

k3s_token: W7hzb52sN7wpDHv2ayzQYfLz4tH2pQvpyg3vKe2iAK577bStCuruqeftKjwkd34
k3s_extra_server_args: --tls-san {{ k3s_vip_api_endpoint }} --flannel-backend=none --disable-network-policy --disable traefik --disable servicelb --selinux

k3s_service_name: k3s.service
k3s_service_state: started
k3s_service_enabled: true

k3s_kube_vip_tag: v0.8.1
k3s_kube_vip_iface: enp6s18

k3s_firewalld_state: enabled
k3s_firewalld_zone: kubernetes
