---
argument_specs:
  main:
    short_description: The main entry point for the helm role.
    options:
      helm_bin_state:
        type: str
        required: false
        choices:
          - present
          - skip
        description: helm_bin_state

      helm_url:
        type: str
        required: false
        description: helm_url

      helm_arch:
        type: str
        required: false
        description: helm_arch

      helm_tag:
        type: str
        required: false
        description: helm_tag

      helm_path:
        type: str
        required: false
        description: helm_path
